### ISSUE TITLE
UDSelect not aligned vertically when Value is set

### ISSUE THREAD

**Issue by kodifan** [ironmansoftware/powershell-universal#4518]
### Description of Issue

As mentioned in powershell universal forum a month ago:
https://forums.ironmansoftware.com/t/powershell-universal-5-3-0/12089/5
when UDSelect has any value set (either chosen from drop down menu or as DefaultValue) this field is not aligned with other fields (like UDTextbox or UDAutocomplete).
This behavior was first observed with 5.3.0 release. Its completely fine on 4.4.0
When UDSelect value  is empty everything is fine. 
Please fix it. I know its a small visual bug but it prevents me from migrating to v5  finally :( 

### Version

5.5.0

### Severity

Low

### Hosting Method

MSI (Windows Service)

### Operating System

Windows

### Database

SQLite

### Licensed

Yes

**Comment by adamdriscoll** [comment]
@kodifan - Can you provide an example that reproduces this issue? I have tried and see them lined up properly. 

```
New-UDApp -Content { 
    New-UDRow -Columns {
        New-UDColumn -LargeSize 3 -Content {
            New-UDSelect -Label 'Test' -Icon (New-UDIcon -Icon User) -Option {
                New-UDSelectOption -Name 1 -Value 1
                New-UDSelectOption -Name 2 -Value 2
            }
        }
        New-UDColumn -LargeSize 3 -Content {
            New-UDAutocomplete -Label 'Test 2' -Icon (New-UDIcon -Icon User) -Options @("1", "2")
        }
    }

 } -Theme (Get-UDTheme -Name 'Paperbase')
```

![Image](https://github.com/user-attachments/assets/73e82055-cd2a-452b-8f7b-f04a9c49b9a4)

**Comment by kodifan** [comment]
hello @adamdriscoll 
its aligned when udselect value is empty
if you choose any value  from drop down menu (or set it with default value) its not

![Image](https://github.com/user-attachments/assets/6954e6ee-be6b-46e8-ba9d-24b15e85f581)

its better seen on default dark theme

PS. as i wrote on forum , i can fix it with:
```
' .MuiListItemText-primary { line-height: 0.8;}'
```
So probably problem also is somewhere there...

**Comment by adamdriscoll** [comment]
This might just be fixed in 5.5.0. We upgraded to the latest version of MUI a couple of weeks ago. Have you tried a more recent version of the nightly 5.5.0? Do you have the nightly build number? I could check. 

This is what I'm seeing on the latest v5.5.0 build. 

![Image](https://github.com/user-attachments/assets/cdd44a71-c24d-4dd8-933b-9df4689edd6c)

**Comment by kodifan** [comment]
I have tried at work on dev server with nightly 5.5.0  build . It was 2-3 days ago ,and result was the same as far as I remember.
Now Im at home , and here I have latest 5.4.0 (i guess) version in docker container.
I will check it later , maybe tomorrow...

PS.I was able to log in remotely. I have 5.5.0 build number 13912591176
and the issue still persist.

**Comment by kodifan** [comment]
i wanted to check this issue with latest 5.5.0 build on my dev server but i've got following errors when installing (updating) :
```
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'duplicate column name: DebugPreference'.
Error 1920. Service 'PowerShell Universal' (PowerShellUniversal) failed to start.  Verify that you have sufficient privileges to start system services.
```

**Comment by kodifan** [comment]
Hello @adamdriscoll 
I ve tried today with latest night build and i still got 'duplicate column name: DebugPreference'.
Is there anything wrong with my database or something has changed in the installer process ?

**Comment by adamdriscoll** [comment]
You'll need to rollback your database schema before running the upgrade. 

https://docs.powershelluniversal.com/getting-started/upgrading#nightly-builds

```
.\psu.exe db schema --schema-version 5.4
```

Optionally, you can delete your database and it will create a new one. This will require reconfiguration of some things.

**Comment by kodifan** [comment]
> You'll need to rollback your database schema before running the upgrade.
> 
> https://docs.powershelluniversal.com/getting-started/upgrading#nightly-builds
> 
> ```
> .\psu.exe db schema --schema-version 5.4
> ```
> 
> Optionally, you can delete your database and it will create a new one. This will require reconfiguration of some things.

Guess i will wait for regular 5.5.0 release;)

**Comment by kodifan** [comment]
@adamdriscoll 
i have tried official 5.5.0 release today  and there is the same error
anything i can do except his command ?
.\psu.exe db schema --schema-version 5.4 

ok i managed to run this command (but proper syntax was like .\psu.exe db schema --schema-version 5.4 -cn "Data Source=c:\ProgramData\UniversalAutomation\database.db")

but issue still remains:
without values

![Image](https://github.com/user-attachments/assets/ce18cf06-bd2a-403e-ad9c-2a5f8fa5b264)

 with values:

![Image](https://github.com/user-attachments/assets/95ab1209-0328-47d4-9298-61d984c0ee5a)

**Comment by adamdriscoll** [comment]
Finally got to the bottom of this one.

**Comment by kodifan** [comment]
> Finally got to the bottom of this one.

out of curiosity - what was the problem ?

**Comment by adamdriscoll** [comment]
There was padding being added to the inner select text that was not there when nothing was selected. The other problem is that if you removed the padding, it would make the select too small. The trick was to both remove the padding and set the minWidth of the  select to the same size as the autocomplete. This makes the select the same size as the autocomplete with and without a value.

**Comment by kodifan** [comment]
> There was padding being added to the inner select text that was not there when nothing was selected. The other problem is that if you removed the padding, it would make the select too small. The trick was to both remove the padding and set the minWidth of the select to the same size as the autocomplete. This makes the select the same size as the autocomplete with and without a value.

upss -  seems complicated. i didn't realize that components look require that much of css tweaking (i fact half of my time now is css tweaking - but i like to customize look and behavior a lot).
ps. will it be avalible is some future nightly 5.6 builds ? or i have to wait for regular 5.6 release ?

**Comment by adamdriscoll** [comment]
The default Ant Design theme is custom and that's why it takes a lot of tweaking. The MaterialDesign is the default and we don't tweak that at all. 

This will be available in tonight's nightly.

**Comment by kodifan** [comment]
tested. have good and bad news :)
its aligned using Ant Design theme:

<img width="481" height="120" alt="Image" src="https://github.com/user-attachments/assets/e441ee4d-ce31-4548-8f6b-0f219838ec46" />

but when using paperbase (MaterialDesign) its not and im using paperabse :(

<img width="472" height="131" alt="Image" src="https://github.com/user-attachments/assets/62a6a05d-e52e-4350-bea7-c4055e28c7b1" />

guess both need some tweaking

**Comment by kodifan** [comment]
@adamdriscoll  still doesn't work with paperbase theme on latest nightly 5.6 build
